{{- if .Values.vault_settings.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: aws-access-key-id
      objectName: aws-access-key-id
    - key: aws-secret-access-key
      objectName: aws-secret-access-key
    - key: azure-form-recognizer-api
      objectName: azure-form-recognizer-api
    - key: azure-form-recognizer-key
      objectName: azure-form-recognizer-key
    - key: gcp-project-id
      objectName: gcp-project-id
    - key: gcp-location
      objectName: gcp-location
    - key: gcp-processor-id
      objectName: gcp-processor-id
    - key: gcp-api-key
      objectName: gcp-api-key
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: sentry-dsn-tables-api
      objectName: sentry-dsn-tables-api
    - key: auth-enabled
      objectName: auth-enabled
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: kafka-sasl-username
      objectName: kafka-sasl-username
    - key: kafka-sasl-password
      objectName: kafka-sasl-password
    secretName: {{ .Values.secrets.deps_tables.secretName }}
    type: Opaque
  parameters:
    roleName: {{ .Values.csi.roleName }}
    vaultAddress: "https://vault"
    vaultNamespace: "vaultNamespace"
    vaultSkipTLSVerify: "true"
    #vaultCACertPath: /csi/issuing_cert
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    objects: |
      - objectName: "aws-access-key-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/aws-credentials"
        secretKey: "aws-access-key-id"

      - objectName: "aws-secret-access-key"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/aws-credentials"
        secretKey: "aws-secret-access-key"

      - objectName: "azure-form-recognizer-api"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/azure-credentials"
        secretKey: "azure-form-recognizer-api"
    
      - objectName: "azure-form-recognizer-key"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/azure-credentials"
        secretKey: "azure-form-recognizer-key"

      - objectName: "gcp-project-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/gcp-credentials"
        secretKey: "gcp-project-id"
      
      - objectName: "gcp-location"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/gcp-credentials"
        secretKey: "gcp-location"

      - objectName: "gcp-processor-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/gcp-credentials"
        secretKey: "gcp-processor-id"

      - objectName: "gcp-api-key"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/gcp-credentials"
        secretKey: "gcp-api-key"

      - objectName: "keycloak-certs-endpoint"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/keycloak-certs-endpoint"
        secretKey: "keycloak-certs-endpoint"

      - objectName: "sentry-dsn-tables-api"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-tables/sentry-dsn-tables-api"
        secretKey: "sentry-dsn-tables-api"

      - objectName: "auth-enabled"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "auth-enabled" 

      - objectName: "message-broker-driver"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-driver"

      - objectName: "message-broker-connection-string"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-connection-string"

      - objectName: "kafka-sasl-username"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/kafka-ssl-secret"
        secretKey: "kafka-sasl-username" 

      - objectName: "kafka-sasl-password"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/kafka-ssl-secret"
        secretKey: "kafka-sasl-password"
{{- end }}  

