apiVersion: v1
kind: Service
metadata:
  name: tables
  labels:
    {{- include "deps-tables.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tables.service.type }}
  ports:
    - port: {{ .Values.tables.service.port }}
      targetPort: {{ .Values.tables.container.portname }}
      protocol: {{ .Values.tables.service.protocol }}
      name: {{ .Values.tables.service.portname }}
  selector:
    {{- include "deps-tables.selectorLabels" . | nindent 4 }}
