apiVersion: apps/v1
kind: Deployment
metadata:
  name: tables-consumer
  labels:
    {{- include "deps-tables.labels" . | nindent 4 }}
    app.kubernetes.io/component: tables-consumer
spec:
  strategy:
    type: {{ .Values.tables_consumer.deployStrategy }}
  replicas: {{ .Values.tables_consumer.replicaCount }}
  selector:
    matchLabels:
      {{- include "deps-tables.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tables-consumer
  template:
    metadata:
      {{- with .Values.tables_consumer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deps-tables.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tables-consumer
    spec:
      {{- if .Values.tables_consumer.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.tables_consumer.imagePullSecrets }}
      {{- end }}
      {{- if .Values.vault_settings.enabled }}
      serviceAccountName: {{ .Values.service_account.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry }}{{ .Values.tables_consumer.image.path }}:{{ .Values.tables_consumer.image.tag | default "latest"}}"
          imagePullPolicy: {{ .Values.tables_consumer.image.pullPolicy }}
          command: [ "python", "-m", "deps_tables", "consume" ]
          envFrom:
            - configMapRef:
                name: tables-configmap
                optional: false
          env:
          - name: OCR_VERSION
            value: {{ .Values.tables_consumer_settings.OCR_VERSION }}
          {{- if .Values.vault_settings.enabled }}
          {{- toYaml .Values.vault_enabled.env | nindent 10 }}
          {{ if .Values.tables_settings.KAFKA_SECURITY_ENABLED }}
          - name: KAFKA_SASL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.deps_tables.secretName }}
                key: kafka-sasl-username
          - name: KAFKA_SASL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.deps_tables.secretName }}
                key: kafka-sasl-password
          {{- end }}
          {{ else }}
          {{- toYaml .Values.vault_disabled.env | nindent 10 }}
          {{ if .Values.tables_settings.KAFKA_SECURITY_ENABLED }}
          - name: KAFKA_SASL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kafka_secrets.secretName }}
                key: kafka-sasl-username
          - name: KAFKA_SASL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.kafka_secrets.secretName }}
                key: kafka-sasl-password
          {{ end }}
          {{- end }}
          readinessProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  if [ "$MESSAGING_DRIVER" == "rabbitmq" ]; then
                    echo > /dev/tcp/$MESSAGING_DRIVER/5672 && echo "RabbitMQ connected" || { echo "RabbitMQ not connected"; exit 1; }
                  fi

                  if [ "$MESSAGING_DRIVER" == "kafka" ]; then
                    echo > /dev/tcp/$(echo "$MESSAGE_BROKER_CONNECTION_STRING" | cut -d':' -f1)/$(echo "$MESSAGE_BROKER_CONNECTION_STRING" | cut -d':' -f2) && echo "Kafka connected" || { echo "Kafka not connected"; exit 1; }
                  fi
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 14
          volumeMounts:
          {{- if .Values.vault_settings.enabled }}
          - name: secrets-store-inline
            mountPath: {{ .Values.secrets_location.secrets_default_path }}
            readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.tables_consumer.resources | nindent 12 }}
      volumes:
      {{- if .Values.vault_settings.enabled }}
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.csi.csi_default_name }}
      {{- end }}
      {{- with .Values.tables.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tables_consumer.affinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ .Values.tables_consumer.affinity.instance}}
              weight: 100
      {{- end }}
      {{- with .Values.tables_consumer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
