version: "3.4"

services:
  tables:
    env_file: etc/deps-tables/env/.test.env #TODO: fix .test.env file
    build:
      context: .
      dockerfile: etc/deps-tables/Dockerfile
      target: develop
    volumes:
      - test-cache:/tmp/test_cache
      - ./src/deps_tables:/app/deps_tables
      - ./src/tests:/app/tests
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./src/setup.cfg:/app/setup.cfg
      - ./vendors:/vendors
      - ./etc/deps-tables/models:/models

  test-rabbitmq:
    image: "${REPOSITORY_URL}/base/rabbitmq:3.7.8-management-alpine"
    environment:
      - RABBITMQ_HOST=test-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=test_deps
      - RABBITMQ_DEFAULT_USER=deps-rabbitmq
      - RABBITMQ_DEFAULT_PASS=deps-rabbitmq-password
      - RABBITMQ_VHOST=test_deps
      - RABBITMQ_USER=deps-rabbitmq
      - RABBITMQ_PASS=deps-rabbitmq-password
    volumes:
      - test-rabbitmq:/var/lib/rabbitmq

volumes:
  test-rabbitmq:
  test-cache:
