tables:
  image:
    path: '/deps-platform/deps-tables'
    pullPolicy: IfNotPresent
  resources: { }
  #  limits:
  #    cpu:
  #    memory:
  #  requests:
  #    cpu:
  #    memory:
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

tables_consumer:
  image:
    path: '/deps-platform/deps-tables'
    pullPolicy: IfNotPresent
  resources: { }
  #  limits:
  #    cpu:
  #    memory:
  #  requests:
  #    cpu:
  #    memory:
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

tables_settings:
  ENV: demo
  SENTRY_TRACES_SAMPLE_RATE: '0.1'
  ENABLED_DETECTION_ENGINES: '["DEPS_DETECTOR","AWS_TEXTRACT","AZURE_FORM_RECOGNIZER","DEPS_CONVERTER"]'
  PAID_ENGINES_RESTRICTION_ENABLED: "false"


csi:
  vault_namespace: 'k8s-demo'
  roleName: 'k8s-demo'
  vaultKubernetesMountPath: 'kubernetes-demo'

service_account:
  serviceAccountName: 'deps-demo'
