tables:
  image:
    path: '/deps-platform/deps-tables'
    pullPolicy: IfNotPresent
  resources: { }
  #  limits:
  #    cpu:
  #    memory:
  #  requests:
  #    cpu:
  #    memory:
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

tables_consumer:
  image:
    path: '/deps-platform/deps-tables'
    pullPolicy: IfNotPresent
  resources: { }
  #  limits:
  #    cpu:
  #    memory:
  #  requests:
  #    cpu:
  #    memory:
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

tables_settings:
  ENV: insurance
  ENABLED_DETECTION_ENGINES: '["DEPS_DETECTOR","DEPS_CONVERTER","AWS_TEXTRACT"]'
  SENTRY_TRACES_SAMPLE_RATE: "0.2"
  PAID_ENGINES_RESTRICTION_ENABLED: "false"

csi:
  vault_namespace: 'k8s-ins'
  roleName: 'k8s-ins'
  vaultKubernetesMountPath: 'kubernetes-ins'

service_account:
  serviceAccountName: 'deps-insurance'
