apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deps-tables
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: tables
    context: ..
    docker: 
      dockerfile: ./etc/deps-tables/Dockerfile
      buildArgs:
        REPOSITORY_URL: ${REPOSITORY_URL}
  local:
    push: false

deploy: 
  helm: 
    releases: 
      - name: deps-tables
        chartPath: ../.helm
        namespace: default
        artifactOverrides:
          image: tables
        valuesFiles: 
        - ./values-tables.yaml
        setValues: 
            registry: ""
        imageStrategy:
          helm: {}
        
        