# Default values for deps-tables.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Secrets declaration
# Precreate them before deploy
# kubectl create secret generic celery-broker-url --from-literal=celery-broker-url=<pyamqp://USERNAME:PASSWORD@RABBITMQ_SERVICE:5672/VHOST>
# kubectl create secret generic celery-backend-url --from-literal=celery-backend-url=<redis://:PASSWORD@REDIS_SERVICE:6379/0>
# kubectl create secret generic aws-credentials --from-literal=aws-access-key-id='<value>' --from-literal=aws-secret-access-key='<value>'
# kubectl create secret generic azure-credentials --from-literal=azure-form-recognizer-api='<value>' --from-literal=azure-form-recognizer-key='<value>'
# kubectl create secret generic keycloak-certs-endpoint --from-literal=keycloak-certs-endpoint='<https://KEYCLOAK_URL/auth/realms/Test/protocol/openid-connect/certs>'
# kubectl create secret generic sentry-dsn-tables --from-literal=sentry-dsn='<SENTRY_DSN_TABLES>'

secrets:
  celery_broker_url:
    secretName: celery-broker-url
  celery_backend_url:
    secretName: celery-backend-url
  aws_credentials:
    secretName: aws-credentials
  azure_credentials:
    secretName: azure-credentials
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  sentry_dsn_tables:
    secretName: sentry-dsn-tables
  auth_enabled:
    secretName: auth-enabled

helm:
  enabled: false

helm_logs_job:
  serviceAccountName: 
  image:
    path: ""
    pullPolicy: IfNotPresent
    tag: ""
  resources: {}

registry: ""

replicaCount: 1
deployStrategy: Recreate
image:
  path: 'tables'
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: 
podAnnotations: {}
service:
  type: ClusterIP
  port: 8000
  portname: 'svc-port'
  protocol: TCP
container:
  port: 8000
  portname: 'cont-port'
  protocol: TCP
resources: {}
nodeSelector: {}
tolerations:
- key: "tables-service"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

affinity:
  enabled: false
  instance: ""

tables_settings:
  ENV: development
  ## Blob storage
  # File Storage (default)
  BLOB_STORAGE: FILE_STORAGE
  # File Blob storage service
  FILE_STORAGE_URL: http://file-storage-nginx:8000/api/storage/v1/file
  OCR_API_URL: http://ocr:8000/api/ocr/v1/extract-text
  AWS_REGION_NAME: 'eu-central-1'
  AZURE_FORM_RECOGNIZER_API: ''
  AZURE_FORM_RECOGNIZER_KEY: ''
  PROJECT_VERSION: 0.2.0
  PREINIT_DETECTORS: false

  # Gunicorn settings
  ## Number of workers
  WORKERS: 1
  ## Reload worker if any code changes
  RELOAD: false
  ## Level of displayed logs
  LOG_LEVEL: info
  ## Maximum number of requests that worker can handle
  MAX_REQUESTS: 1000
  ## Timeout for one request (in seconds)
  TIMEOUT: 600

  # Sentry settings
  SENTRY_ENABLED: 'true'
  SENTRY_TRACES_SAMPLE_RATE: '1.0'

  ## Set debug to true for local development and running
  DEBUG: false

  # Machine learning models settings
  ENABLE_GPU: false
  # border identification allows to verify that image has at least one table
  # and it means that we can get coordinates of this table
  IDENTIFY_TABLE_BORDERS: true

  # Auth
  AUTH_VERIFY_SSL: false

  ENABLED_DETECTION_ENGINES: '["DEPS_DETECTOR"]'
